# Generated by Django 6.0.6 on 2026-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='Good Life Pharmacy', max_length=200)),
                ('pharmacy_tagline', models.CharField(default='Your Health, Our Priority', max_length=200)),
                ('pharmacy_address', models.TextField(default='123 Health Street, Juba')),
                ('pharmacy_phone', models.CharField(default='+211 123 456 789', max_length=20)),
                ('pharmacy_email', models.EmailField(default='info@pharmacy.com', max_length=254)),
                ('receipt_footer', models.CharField(default='Thank you for choosing us!', max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('currency', models.CharField(default='SSP', max_length=3)),
                ('usd_to_ssp_rate', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('show_both_currencies', models.BooleanField(default=True)),
                ('low_stock_alert', models.IntegerField(default=20)),
                ('expiry_alert_days', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacy Settings',
                'db_table': 'pharmacy_settings',
            },
        ),
    ]
